# Generated by Django 4.1.7 on 2023-03-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contact_created_at_contact_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='job',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
