# Generated by Django 4.1.7 on 2023-03-08 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='messag',
            new_name='message',
        ),
    ]
